### PR TITLE
Default names

### PR DESCRIPTION
**Pull request by gajowi**
https://github.com/cloudalchemy/ansible-process_exporter/issues/10

### CODE REVIEW

**Comment by gajowi** [comment]
I see the problem caught by Yamllimt. Unfortunately I've only had partial success getting CI set up in my fork so I did not see it earlier.  More reading now to see how to update my PR..

**Comment by gajowi** [comment]
Ha. The deb/rpm default breaks ansible templating. That has implications for any user who wants to use the process-exporter documented templating, so the right fix is to change the use of ansible templating to not break on the recommended syntax.  This will need some more thought - and motivate me to improve my testing process :-). So this is stalled for the moment.

**Comment by gajowi** [comment]
I did something creative to handle the process-exporter recommended Template variables. I think it is a reasonable solution. Probably I should make an additional documentation change to explain that special care is needed _if_ such variables are used. I personally don't intend to use them but surely others will and the role should be made to work for expected common cases.
So I'll add another commit soon.
I hope/suspect the series of commits can be squashed when the PR is accepted. Not sure how to do that myself without crazy manual process.

**Comment by paulfantom** [comment]
Yeah, that's because `{{ ... }}` is evaluated by jinja2 so you end up with not a direct copy, but with something else.

**Comment by paulfantom** [comment]
As for squashing, it should be enabled in all cloudalchemy repos as a default PR merging method. :)

**Pull request merged**
